/*
   -- New project --
   
   To compile this code using RemoteXY library 4.1.4 or later version 
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/                   
     - for ANDROID 4.16.02 or later version;
     - for iOS 1.13.1 or later version;
    
   To interact with the GUI, please refer to the manual: 
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and 
   is an example for the RemoteXY library. 
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license 
   details.             
*/

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG    

// RemoteXY select connection mode and include library 
#define REMOTEXY_MODE__WIFI_CLOUD

#include <ESP8266WiFi.h>

// RemoteXY connection settings 
#define REMOTEXY_WIFI_SSID "iPhone"
#define REMOTEXY_WIFI_PASSWORD "zhang044680"
#define REMOTEXY_CLOUD_SERVER "cloud.remotexy.com"
#define REMOTEXY_CLOUD_PORT 6376
#define REMOTEXY_CLOUD_TOKEN "e1b27236781afa830a004bef1888ec01"
#define R_PIN D5
#define G_PIN D6
#define B_PIN D7

#include <RemoteXY.h>

// RemoteXY GUI configuration  
#pragma pack(push, 1)  
uint8_t RemoteXY_CONF[] =   // 61 bytes
  { 255,4,0,0,0,54,0,19,0,0,0,0,31,1,106,200,1,1,4,0,
  4,16,43,17,51,0,2,26,4,45,42,17,51,0,2,26,4,73,41,17,
  52,0,2,26,2,30,131,44,22,0,2,26,31,31,79,78,0,79,70,70,
  0 };
  
// this structure defines all the variables and events of your control interface 
struct {

    // input variables
  int8_t slider_R; // from 0 to 100
  int8_t slider_G; // from 0 to 100
  int8_t slider_B; // from 0 to 100
  uint8_t switch_01; // =1 if switch ON and =0 if OFF, from 0 to 1

    // other variable
  uint8_t connect_flag;  // =1 if wire connected, else =0

} RemoteXY;   
#pragma pack(pop)
 
/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////



void setup() 
{
  RemoteXY_Init ();
  Serial.begin(9600);
  pinMode(R_PIN, OUTPUT);
  pinMode(G_PIN, OUTPUT);
  pinMode(B_PIN, OUTPUT);
  analogWriteRange(255);
  
  // TODO you setup code
  
}

void loop() 
{ 
  RemoteXY_Handler ();
  if (RemoteXY.switch_01 == 0) {
    analogWrite(R_PIN, 0);
    analogWrite(G_PIN, 0);
    analogWrite(B_PIN, 0);
    Serial.print("No");
  } else{
    analogWrite(R_PIN, RemoteXY.slider_R);
    analogWrite(G_PIN, RemoteXY.slider_G);
    analogWrite(B_PIN, RemoteXY.slider_B);
    Serial.print("OK");
  }
  RemoteXY_delay(200);
  // TODO you loop code
  // use the RemoteXY structure for data transfer
  // do not call delay(), use instead RemoteXY_delay() 


}
