/*
   -- New project --
   
   To compile this code using RemoteXY library 4.1.4 or later version 
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/                   
     - for ANDROID 4.16.02 or later version;
     - for iOS 1.13.1 or later version;
    
   To interact with the GUI, please refer to the manual: 
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and 
   is an example for the RemoteXY library. 
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license 
   details.             
*/

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG    

// RemoteXY select connection mode and include library 
#define REMOTEXY_MODE__WIFI_CLOUD

#include <ESP8266WiFi.h>

// RemoteXY connection settings 
#define REMOTEXY_WIFI_SSID "iPhone"
#define REMOTEXY_WIFI_PASSWORD "zhang044680"
#define REMOTEXY_CLOUD_SERVER "cloud.remotexy.com"
#define REMOTEXY_CLOUD_PORT 6376
#define REMOTEXY_CLOUD_TOKEN "1bb1c17920ec49fb15fddae2a028f662"


#include <RemoteXY.h>
#define SOIL_PIN A0
int critical_value = 1020;
// RemoteXY GUI configuration  
#pragma pack(push, 1)  
uint8_t RemoteXY_CONF[] =   // 47 bytes
  { 255,0,0,6,0,40,0,19,0,0,0,0,31,1,106,200,1,1,3,0,
  67,33,43,40,10,78,2,26,2,70,16,100,18,18,16,26,37,0,70,66,
  99,18,18,16,26,120,0 };
  
// this structure defines all the variables and events of your control interface 
struct {

    // output variables
  float value_01;
  uint8_t led_01; // from 0 to 1
  uint8_t led_02; // from 0 to 1

    // other variable
  uint8_t connect_flag;  // =1 if wire connected, else =0

} RemoteXY;   
#pragma pack(pop)
 
/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////



void setup() 
{
  RemoteXY_Init (); 
  Serial.begin(9600);
  pinMode(SOIL_PIN, INPUT);
  
  // TODO you setup code
  
}

void loop() 
{ 
  RemoteXY_Handler ();
  float soil = analogRead(SOIL_PIN);
  RemoteXY.value_01 = soil;
  Serial.print("Soil moisture = ");
  Serial.println(soil);

  if (soil < critical_value) {
    RemoteXY.led_01 = 1; 
    RemoteXY.led_02 = 1; 
  }
  else {
    RemoteXY.led_01 = 0;
    RemoteXY.led_02 = 0;
  }

  RemoteXY_delay(200);
  
  // TODO you loop code
  // use the RemoteXY structure for data transfer
  // do not call delay(), use instead RemoteXY_delay() 


}



